main: cgitest.cpp httpdserver.cpp
	g++ -o 1_hw3 cgitest.cpp
	g++ -o 2_hw3 httpdserver.cpp
	g++ -o print_env print_env.cpp
	chmod +x ./1_hw3
	chmod +x ./print_env
	cp ./1_hw3 /var/www/cgi-bin/
	cp ./print_env /var/www/cgi-bin/
